### ISSUE TITLE
Unresolved conflicts in recent code 

### ISSUE THREAD

**Issue by g1itch** [BTA-BATA/BATA-SOURCE#11]
[line 787](/BTA-BATA/BATA-SOURCE/blob/master/src/serialize.h#L787) in serialize.h
[line 8](/BTA-BATA/BATA-SOURCE/blob/master/src/clientversion.h#L8) in clientversion.h
[line 37](/BTA-BATA/BATA-SOURCE/blob/master/src/net.h#L37) in net.h

**Comment by midnight-miner** [comment]
Pull Request made:
https://github.com/BTA-BATA/BATA-SOURCE/pull/12
