### ISSUE TITLE
Crash after "addnode" rpc call

### ISSUE THREAD

**Issue by erasmospunk** [BTA-BATA/BATA-SOURCE#19]
When I am trying to add a node the process crashes.

I am compiling from source and running it in a docker container.

**Comment by erasmospunk** [comment]
After a resync it seems to be working again

**Comment by erasmospunk** [comment]
no, still crashes

**Comment by BTA-BATA** [comment]
Hi John we will release 10.5 soon which will address the crashing.

**Comment by erasmospunk** [comment]
So you are aware of it?

I did some more testing and it seems to be happening when running several `addnode <IP-address> onetry` commands. When running `addnode <IP-address> add` it doesn't crash but the peers are not added.

**Comment by BTA-BATA** [comment]
Closing a 10.5 addresses issues raised.

**Comment by BTA-BATA** [comment]
Code ready to update Coinomi wallet. Thanks
