### ISSUE TITLE
DNS seed returns a single node

### ISSUE THREAD

**Issue by erasmospunk** [BTA-BATA/BATA-SOURCE#20]
When trying to sync with the rest of the network, I can't pass single DNS seed node, leaving me with a single connection.

**Comment by BTA-BATA** [comment]
Hi John,

Download http://biznaturally.ca/crypto/bata.conf.zip for a list of peers.

**Comment by BTA-BATA** [comment]
Just a reminder to set rpcusername and password as it is not in conf. file.

**Comment by BTA-BATA** [comment]
Closing a 10.5 addresses issues raised.
