### ISSUE TITLE
Wallet is constantly Crashing on Windows 2012 R2 64bit

### ISSUE THREAD

**Issue by Virtuworks** [BTA-BATA/BATA-SOURCE#45]
Running Solo mining using core wallet on windows results in constant crashing where we need to restart the wallet to continue mining. Looking for some guidance on how to get past this issue.

**Comment by BTA-BATA** [comment]
Thanks we are in final testing of 10.5.1 https://github.com/BTA-BATA/BATA-SOURCE/releases which addresses the issue.

**Comment by Virtuworks** [comment]
![image](https://user-images.githubusercontent.com/12708326/29346304-57445960-8212-11e7-94b0-1ad5b05dea39.png)

**Comment by midnight-miner** [comment]
Solo mining meaning using the wallet itself to mine coins?
This is no longer supported as the computer CPUs will not compete with ASIC mining.

**Comment by Virtuworks** [comment]
https://beta.hashwiz.io/pool/BTA/

No - I've setup a pool and I am trying to Mine with an ASIC Antminer L3+

**Comment by midnight-miner** [comment]
OK, good.  Not really solo mining then.
10.4 is tested on mining pool (by me)

**Comment by Virtuworks** [comment]
Ok cool thanks I will try 10.4 and move back for now see how that goes. I appreciate it!

**Comment by midnight-miner** [comment]
I have a pool running 10.4 at pool.midnightminer.net

**Comment by Virtuworks** [comment]
@midnight-miner seems like they don't have a windows binary on 10.4 from what I can tell.

**Comment by midnight-miner** [comment]
Sorry, try 10.4.1
https://github.com/BTA-BATA/BATA-SOURCE/releases

**Comment by Virtuworks** [comment]
@midnight-miner I already had tried 10.4.1 and it had given me same issue, but it did work much better than latest version. I've moved back but can't really mine in any capacity because of this.

**Comment by midnight-miner** [comment]
You can point your miner to pool.midnightminer.net to mine.  only 1% fee.

**Comment by Virtuworks** [comment]
It's ok, I am working on coding this Mining pool at in the meantime I will Mine another coin to do my testing. I appreciate it!

**Comment by midnight-miner** [comment]
Are you using a Windows based mining pool?  Most pools and wallets run on Linux.  I have not seen much support for Windows.

**Comment by Virtuworks** [comment]
Yes, I've taken the source code from a Linux/Windows C# project and improved it. It runs on IIS/.NET Core/MVC/REDIS and has a Windows Service based Stratum Agent that connects to the Pools Portal. I also noticed the same thing with Windows, Figured I would take a stab at changing that fact and bring some Windows Support to the Table. It's based on a source code originally called CoiniumServ. I've probably replaced 70% of the code so far on cleaning it up.

**Comment by Virtuworks** [comment]
this is not completed, we have same issue with 10.4.1

**Comment by midnight-miner** [comment]
This is interesting.
Windows testing I only have Win 7, Win 8.1, and Win10.  I am attempting to resurrect a 2008 server for testing, but it is still probably a week away.

**Comment by Virtuworks** [comment]
@midnight-miner with Windows 2012 R2, it crashes every 12-20 hours on 10.4.1 - with 10.5.1 it doesn't last 20 minutes.

**Comment by midnight-miner** [comment]
I had issues similar when testing on Mac.
We have committed many changes to my Github account for testing before committing it to the BTA-BATA repo.  
I could sent you a test build to try out if your interested.

**Comment by Virtuworks** [comment]
Happy to do so if that was available.

Sent from my iPhone

On Aug 17, 2017, at 12:44 AM, MidnightMiner <notifications@github.com<mailto:notifications@github.com>> wrote:


I had issues similar when testing on Mac.
We have committed many changes to my Github account for testing before committing it to the BTA-BATA repo.
I could sent you a test build to try out if your interested.

-

**Comment by midnight-miner** [comment]
Pre-release binaries are available here:
https://github.com/midnight-miner/BATA-Development/releases/tag/v0.10.5.1rc1

**Comment by Virtuworks** [comment]
@midnight-miner So far on this version seems like it's working good! No crash so far in 7 hours I will keep you posted.

**Comment by Virtuworks** [comment]
@midnight-miner was just looking at your changes, that's actually quite funny that they hadn't done that up to this point lol I guess it's that easy to clone and go a coin. I guess the problem I was having could stem from also having the LTC wallet core running on the same server? My stratum is running multiple Wallets on it so this conflict makes a lot of sense. Good catch!

**Comment by BTA-BATA** [comment]
Closing - Let us know if you experience anymore issues and I will reopen. Thanks.
