### ISSUE TITLE
BATA is loosing connection all the time to Network with Socket errors

### ISSUE THREAD

**Issue by Virtuworks** [BTA-BATA/BATA-SOURCE#47]
![image](https://user-images.githubusercontent.com/12708326/29457301-92dc3c00-83e7-11e7-8b76-315c0d8ba113.png)

Bata Pool return to OK in several minutes usually

![image](https://user-images.githubusercontent.com/12708326/29457277-840ac5c0-83e7-11e7-9bc2-66d00eb85f75.png)

I think it is related coin\debug.log

**Comment by Virtuworks** [comment]
@midnight-miner more issues friend!

**Comment by BTA-BATA** [comment]
Hello again, thanks for contacting us and letting us know.
Are you able to try this release which will stop any flooding:

https://github.com/JustinPercy/BATA-Development/releases

**Comment by Virtuworks** [comment]
Alex see below please check this version.

Does this version include the changes from midnightminer?

Sent from my iPhone

On Aug 18, 2017, at 8:51 AM, pc888 <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello again, thanks for contacting us and letting us know.
Are you able to try this release which will stop any flooding:

https://github.com/JustinPercy/BATA-Development/releases<https://github.com/JustinPercy/BATA-Development/releases>

-

**Comment by BTA-BATA** [comment]
Alex? Not sure who you are referring to. To answer your question yes it does.

**Comment by Virtuworks** [comment]
Alex is my developer I CC him on message – Thx!

**Comment by BTA-BATA** [comment]
ok no worries 👍

**Comment by midnight-miner** [comment]
Virtuworks ,
I am curious to know if there was a reason you used Litecoin-cli.exe for the RPC calls?
I think I had the bata-cli.exe in the zip.

I have my Windows Small Business Server 2008 up and running... Another platform to test on.

**Comment by Virtuworks** [comment]
I'll point out your comments to my developer and get back to you.

**Comment by Virtuworks** [comment]
Latest seems to fix all issues!

**Comment by Virtuworks** [comment]
@midnight-miner the dev tells me he was using CLI for testing only, we interface RPC calls via Port on Pool.
