### ISSUE TITLE
Wallet constantly crashing on Windows 

### ISSUE THREAD

**Issue by Virtuworks** [BTA-BATA/BATA-SOURCE#55]
Wallet is still constantly crashing on Windows

**Comment by midnight-miner** [comment]
I am having an issue on a Linux machine with wallet crashing after several hours or a day of running.  Looking into possible causes.  

How long is you wallet running approx. before crashing?

**Comment by Virtuworks** [comment]
16-20 hours

Sent from my iPhone

On Sep 3, 2017, at 12:49 AM, MidnightMiner <notifications@github.com<mailto:notifications@github.com>> wrote:


I am having an issue on a Linux machine with wallet crashing after several hours or a day of running. Looking into possible causes.

How long is you wallet running approx. before crashing?

-

**Comment by midnight-miner** [comment]
OK.  About the same on my Linux machine.  I will get you an exe for Win64 tomorrow that should improve the situation.

**Comment by Virtuworks** [comment]
Thx!

Sent from my iPhone

On Sep 3, 2017, at 1:16 AM, MidnightMiner <notifications@github.com<mailto:notifications@github.com>> wrote:


OK. About the same on my Linux machine. I will get you an exe for Win64 tomorrow that should improve the situation.

-

**Comment by midnight-miner** [comment]
Pre-release Win64 executable is available here:
https://github.com/midnight-miner/BATA-Development/releases/tag/0.10.5.2

**Comment by midnight-miner** [comment]
Pre-release Win64 executable is available here:
https://github.com/midnight-miner/BATA-Development/releases

**Comment by Virtuworks** [comment]
Will do, about to get hammered by Irma in miami as soon as we are on other side or done hunkering down.

**Comment by midnight-miner** [comment]
I wish you the best.  I hope all works out and you and yours are safe.
